name: Reusable workflow for 1 test

on:
  workflow_call:
    inputs:
      filestem:
        required: true
        type: string

jobs:
  test-a-tutorial:
    runs-on: ubuntu-latest

    steps:
      # 1. create xmls from *.lphy
      - name: Create xmls
        # added -Dbeast.user.package.dir=$LPHY_BEAST_DIR into bin/lphybeast
        # use absolute path
        run: |
          echo ${{ inputs.filestem }}
          mkdir $XML_DIR
          $BEAST/bin/lphybeast -l 10000000 -o $XML_DIR/${{ inputs.filestem }}.xml $LPHY_SCRIPTS/${{ inputs.filestem }}.lphy

      # 2. run xmls, WD is still /home/runner/work/LPhyBeastTest/LPhyBeastTest
      - name: Run xmls
        # added -Dbeast.user.package.dir=$GITHUB_WORKSPACE/beast2 into bin/beast
        run: |
          pwd
          echo "ls $XML_DIR"
          ls $XML_DIR
          $BEAST/bin/beast -working $XML_DIR/${{ inputs.filestem }}.xml

      # 3. post analyses
      - name: Analyse log and Annotate trees
        run: |
          cd $XML_DIR
          ls .
          $BEAST/bin/loganalyser ${{ inputs.filestem }}.log
          $BEAST/bin/treeannotator -burnin 10 -heights mean ${{ inputs.filestem }}.trees ${{ inputs.filestem }}.tree
