name: LPhy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

# not support var in the path
env:
  BEAST_DIR: beast2.6.7
  LPHY_DIR:  lphy-studio-1.3.0

jobs:
  setup-lphybeast:
    runs-on: ubuntu-latest

    # note: not support var containing var
    # $BEAST is reserved in all scripts
    steps:
      - name: Set environmental variables
        run: |
          echo "BEAST=$GITHUB_WORKSPACE/$BEAST_DIR" >> $GITHUB_ENV
          echo "LPHY_SCRIPTS=$GITHUB_WORKSPACE/$BEAST_DIR/$LPHY_DIR/tutorials" >> $GITHUB_ENV
          echo "LPHY_BEAST_DIR=$GITHUB_WORKSPACE/beast2" >> $GITHUB_ENV
          echo "XML_DIR=$GITHUB_WORKSPACE/lphybeast" >> $GITHUB_ENV

      - name: Checkout main
        uses: actions/checkout@v2
      # this must be after main
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          #cache: 'gradle'

      # install lphybeast, lphybeast-ext https://www.beast2.org/managing-packages/
      # added -Dbeast.user.package.dir=$LPHY_BEAST_DIR into bin/packagemanager
      # $BEAST_DIR/bin/packagemanager -list
      - name: Install lphybeast
        run: |
          pwd
          echo "ls $BEAST"
          ls $BEAST
          $BEAST/bin/packagemanager -dir $LPHY_BEAST_DIR -add lphybeast
          $BEAST/bin/packagemanager -dir $LPHY_BEAST_DIR -add LPhyBeastExt
          echo "ls $LPHY_BEAST_DIR"
          ls $LPHY_BEAST_DIR
          echo "ls $LPHY_SCRIPTS"
          ls $LPHY_SCRIPTS

  test-RSV2:
    needs: setup-lphybeast
    uses: ./.github/workflows/reusable-test.yml
    with:
      filestem: RSV2
