name: LPhy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

# not support var in the path
env:
  BEAST_DIR: beast2.6.7
  LPHY_DIR:  lphy-studio-1.3.0

jobs:
  setup-lphybeast:
    # libgfortran3 not available in ubuntu-last
    runs-on: ubuntu-18.04

    # note: not support var containing var
    # $BEAST is reserved in all scripts
    steps:
      - name: Set environmental variables
        run: |
          echo "BEAST=$GITHUB_WORKSPACE/$BEAST_DIR" >> $GITHUB_ENV
          echo "LPHY_SCRIPTS=$GITHUB_WORKSPACE/$BEAST_DIR/$LPHY_DIR/tutorials" >> $GITHUB_ENV
          echo "LPHY_BEAST_DIR=$GITHUB_WORKSPACE/beast2" >> $GITHUB_ENV
          echo "XML_DIR=$GITHUB_WORKSPACE/lphybeast" >> $GITHUB_ENV

      - name: Checkout main
        uses: actions/checkout@v3
      # this must be after main
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # install lphybeast, lphybeast-ext https://www.beast2.org/managing-packages/
      # added -Dbeast.user.package.dir=$LPHY_BEAST_DIR into bin/packagemanager
      # $BEAST_DIR/bin/packagemanager -list
      - name: Install lphybeast
        run: |
          pwd
          echo "ls $BEAST"
          ls $BEAST
          $BEAST/bin/packagemanager -dir $LPHY_BEAST_DIR -add lphybeast
          $BEAST/bin/packagemanager -dir $LPHY_BEAST_DIR -add LPhyBeastExt
          echo "ls $LPHY_BEAST_DIR"
          ls $LPHY_BEAST_DIR
          head -1 $(find $LPHY_BEAST_DIR -name 'version.xml' -print)
          echo "ls $LPHY_SCRIPTS"
          ls $LPHY_SCRIPTS

      - name: h5n1
        run: |
          $BEAST/bin/lphybeast -l 10000000 -o $XML_DIR/h5n1.xml $LPHY_SCRIPTS/h5n1.lphy
          cd $XML_DIR
          $BEAST/bin/beast -working h5n1.xml
          ls -l
          $BEAST/bin/loganalyser h5n1.log 
          $BEAST/bin/treeannotator -burnin 20 -heights mean h5n1_with_trait.trees h5n1_with_trait.tree

      - name: h5n1 estimating transitions
        # require Babel for StateTransitionCounter
        run: |
          $BEAST_DIR/bin/packagemanager -add Babel
          cd $XML_DIR
          $BEAST/bin/applauncher StateTransitionCounter -burnin 20 -in h5n1_with_trait.trees -tag location -out h5n1.stc.out
          cat h5n1.stc.out

      #TODO: JRE crashes using beagle for h5n1.xml
      # use beagle 3.0.1
      - name: Build beagle
        run: |
          pwd
          git clone --branch v3.0.1 --depth=1 https://github.com/beagle-dev/beagle-lib.git
          cd beagle-lib
          sudo ./autogen.sh
          sudo ./configure --prefix=/usr/local
          sudo make install
          sudo ldconfig
          $BEAST/bin/beast -beagle_info

      - name: RSV2
        run: |
          pwd
          $BEAST/bin/lphybeast -l 2000000 -o $XML_DIR/RSV2.xml $LPHY_SCRIPTS/RSV2.lphy
          cd $XML_DIR
          $BEAST/bin/beast -working -beagle_SSE RSV2.xml
          ls -l
          $BEAST/bin/loganalyser RSV2.log
          $BEAST/bin/treeannotator -burnin 20 -heights mean RSV2.trees RSV2.tree

      - name: hcv_coal
        run: |
          $BEAST/bin/lphybeast -o $XML_DIR/hcv_coal.xml $LPHY_SCRIPTS/hcv_coal.lphy
          cd $XML_DIR
          $BEAST/bin/beast -working -beagle_SSE hcv_coal.xml
          ls -l
          $BEAST/bin/loganalyser hcv_coal.log
          $BEAST/bin/treeannotator -burnin 20 -heights mean hcv_coal.trees hcv_coal.tree

#      # libgfortran5 is not working
#      - name: Install libgfortran3
#        run: sudo apt-get install libgfortran3
#      - name: h3n2
#        run: |
#          $BEAST/bin/lphybeast -o $XML_DIR/h3n2.xml $LPHY_SCRIPTS/h3n2.lphy
#          cd $XML_DIR
#          $BEAST/bin/beast -working -beagle_SSE h3n2.xml
#          ls -l
#          $BEAST/bin/loganalyser h3n2.log
#          $BEAST/bin/treeannotator -burnin 20 -heights mean h3n2.trees h3n2.tree

      # check all *.summary.txt and *.tree
      - name: Test logs and trees
        run: ./gradlew test --no-daemon
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./**/build/test-results/**/*.xml
