name: LPhy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

# not support var in the path
env:
  BEAST: beast2.6.7
  LPHY:  lphy-studio-1.3.0

jobs:
  test-lphybeast-tutorials:
    runs-on: ubuntu-latest

    # note: not support var containing var
    steps:
      - name: Set environmental variables
        run: |
          echo "BEAST_DIR=$GITHUB_WORKSPACE/$BEAST" >> $GITHUB_ENV
          echo "LPHY_SCRIPTS=$GITHUB_WORKSPACE/$BEAST/$LPHY/tutorials" >> $GITHUB_ENV
          echo "LPHY_BEAST_DIR=$GITHUB_WORKSPACE/beast2" >> $GITHUB_ENV
          echo "XML_DIR=$GITHUB_WORKSPACE/lphybeast" >> $GITHUB_ENV

      - name: Checkout main
        uses: actions/checkout@v2
      # this must be after main
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          #cache: 'gradle'

      # 1. install lphybeast, lphybeast-ext https://www.beast2.org/managing-packages/
      # added -Dbeast.user.package.dir=$LPHY_BEAST_DIR into bin/packagemanager
      # $BEAST_DIR/bin/packagemanager -list
      - name: Install lphybeast
        run: |
          pwd
          echo "ls $BEAST_DIR"
          ls $BEAST_DIR
          $BEAST_DIR/bin/packagemanager -dir $LPHY_BEAST_DIR -add lphybeast
          $BEAST_DIR/bin/packagemanager -dir $LPHY_BEAST_DIR -add LPhyBeastExt
          echo "ls $LPHY_BEAST_DIR"
          ls $LPHY_BEAST_DIR
          echo "ls $LPHY_SCRIPTS"
          ls $LPHY_SCRIPTS

      # 2. create xmls from *.lphy
      - name: Create xmls
        # added -Dbeast.user.package.dir=$LPHY_BEAST_DIR into bin/lphybeast
        # use absolute path
        run: |
          mkdir $XML_DIR
          cd $XML_DIR
          pwd
          $BEAST_DIR/bin/lphybeast -o ./RSV2.xml $LPHY_SCRIPTS/RSV2.lphy

      # 3. run xmls
      - name: Run xmls
        # added -Dbeast.user.package.dir=$GITHUB_WORKSPACE/beast2 into bin/beast
        run: |
          pwd
          ls .
          $BEAST_DIR/bin/beast -working RSV2.xml
          
      # 4. log analyser
      - name: Analyse log
        working-directory: ${{env.XML_DIR}}
        run: |
          ls .
          $BEAST_DIR/bin/loganalyser RSV2.log

      - name: Annotate tree
        working-directory: ${{env.XML_DIR}}
        run: |
          $BEAST_DIR/bin/treeannotator -burnin 10 -heights mean RSV2.trees RSV2.tree
          

