name: LPhy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

# https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  # $GITHUB_WORKSPACE = /home/runner/work/LPhyBeastTest/LPhyBeastTest
  BEAST: $GITHUB_WORKSPACE/beast2.6.7
  LPHY_BEAST_DIR: $GITHUB_WORKSPACE/beast2
  LPHY_SCRIPTS: $BEAST/lphy-studio-1.3.0/tutorials
  XML_DIR: $GITHUB_WORKSPACE/lphybeast

jobs:
  test-lphybeast-tutorials:
    runs-on: ubuntu-latest

    steps:
      - name: Set environmental variables
        run: |
          echo "BEAST=$GITHUB_WORKSPACE/beast2.6.7" >> $GITHUB_ENV
          echo "LPHY_BEAST_DIR=$GITHUB_WORKSPACE/beast2" >> $GITHUB_ENV
          echo "LPHY_SCRIPTS=$BEAST/lphy-studio-1.3.0/tutorials" >> $GITHUB_ENV
          echo "XML_DIR=$GITHUB_WORKSPACE/lphybeast" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      - name: Checkout main
        uses: actions/checkout@v3
      # 1. install lphybeast, lphybeast-ext
      # https://www.beast2.org/managing-packages/
      - name: Install lphybeast
        run: |
          pwd
          ls $BEAST
          $BEAST/bin/packagemanager -dir $LPHY_BEAST_DIR -add lphybeast
          $BEAST/bin/packagemanager -dir $LPHY_BEAST_DIR -add LPhyBeastExt
          ls $LPHY_BEAST_DIR
          $BEAST/bin/packagemanager -list

      # 2. create xmls from *.lphy
      - name: Create xmls
        # add -Dbeast.user.package.dir=$LPHY_BEAST_DIR into bin/lphybeast
        # use absolute path
        run: |
          mkdir $XML_DIR
          $BEAST/bin/lphybeast -o $XML_DIR/RSV2.xml $LPHY_SCRIPTS/RSV2.lphy


      # 3. run xmls
      - name: Create xmls
        # add -Dbeast.user.package.dir=$GITHUB_WORKSPACE/beast2 into bin/beast
        run: |
          ls $XML_DIR
          $BEAST/bin/beast $XML_DIR/RSV2.xml
          
          

#      - name: Publish unit test results
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        if: always()
#        with:
#          files: ./LPhyBeast/*/build/test-results/**/*.xml