name: LPhy BEAST tests
on: [ push, pull_request, workflow_dispatch ]

# not support var in the path
env:
  BEAST_DIR: beast2.6.7
  LPHY_DIR:  lphy-studio-1.3.1
  SEED:      777
  # true, then use prerelease.xml for snapshot versions; or false, then use CBAN
  PRERELEASE:      true

jobs:
  setup-lphybeast:
    # libgfortran3 not available in ubuntu-last
    runs-on: ubuntu-18.04

    # note: not support var containing var
    # $BEAST is reserved in all scripts
    steps:
      - name: Set environmental variables
        run: |
          echo "BEAST=$GITHUB_WORKSPACE/$BEAST_DIR" >> $GITHUB_ENV
          echo "LPHY_SCRIPTS=$GITHUB_WORKSPACE/$BEAST_DIR/$LPHY_DIR/tutorials" >> $GITHUB_ENV
          echo "LPHY_BEAST_DIR=$GITHUB_WORKSPACE/beast2" >> $GITHUB_ENV
          echo "XML_DIR=$GITHUB_WORKSPACE/lphybeast" >> $GITHUB_ENV

      - name: Checkout main
        uses: actions/checkout@v3
      # this must be after main
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      # if beast2 folder has zip, then use prerelease.xml
      - name: Setup packages.url
        run: |
          pwd
          echo $PRERELEASE
          cd $LPHY_BEAST_DIR
          ls -l
          if [ "${PRERELEASE,,}" = true ]; then
            echo 'packages.url=https://github.com/LinguaPhylo/LPhyBeastTest/raw/main/beast2/prerelease.xml' > beauti.properties
            echo 'Testing SNAPSHOT versions ...'        
          fi
          cat beauti.properties
          

      # install lphybeast, lphybeast-ext https://www.beast2.org/managing-packages/
      # add -Dbeast.user.package.dir=$LPHY_BEAST_DIR into bin/packagemanager
      # $BEAST/bin/packagemanager -list
      - name: Install lphybeast
        run: |
          pwd
          echo "ls $BEAST"
          ls $BEAST
          $BEAST/bin/packagemanager -add lphybeast
          $BEAST/bin/packagemanager -add LPhyBeastExt
          $BEAST/bin/packagemanager -list
          echo "ls $LPHY_BEAST_DIR"
          ls $LPHY_BEAST_DIR
          head -1 $(find $LPHY_BEAST_DIR -name 'version.xml' -print)
          echo "ls $LPHY_SCRIPTS"
          ls $LPHY_SCRIPTS

      # use beagle 3.1.2
      - name: Build beagle
        run: |
          pwd
          git clone --branch v3.1.2 --depth=1 https://github.com/beagle-dev/beagle-lib.git
          cd beagle-lib
          sudo ./autogen.sh
          sudo ./configure --prefix=/usr/local
          sudo make install
          sudo ldconfig
          $BEAST/bin/beast -beagle_info

      - name: h5n1
        # -l 3,000,000
        run: |
          $BEAST/bin/lphybeast -l 3000000 -o $XML_DIR/h5n1.xml $LPHY_SCRIPTS/h5n1.lphy
          cd $XML_DIR
          $BEAST/bin/beast -working -beagle_SSE -seed $SEED h5n1.xml
          ls -l
          $BEAST/bin/loganalyser h5n1.log 
          $BEAST/bin/treeannotator -burnin 10 -heights mean h5n1_with_trait.trees h5n1_with_trait.tree
          LOC_TREE=$(tail -2 h5n1_with_trait.tree | head -1)
          echo ${LOC_TREE: -800}

      - name: h5n1 estimating transitions
        # require Babel for StateTransitionCounter
        run: |
          $BEAST_DIR/bin/packagemanager -add Babel
          cd $XML_DIR
          $BEAST/bin/applauncher StateTransitionCounter -burnin 10 -in h5n1_with_trait.trees -tag location -out h5n1.stc.out
          cat h5n1.stc.out

      - name: RSV2
        # -l 20,000,000
        run: |
          pwd
          $BEAST/bin/lphybeast -l 5000000 -o $XML_DIR/RSV2.xml $LPHY_SCRIPTS/RSV2.lphy
          cd $XML_DIR
          $BEAST/bin/beast -working -beagle_SSE -seed $SEED RSV2.xml
          ls -l
          $BEAST/bin/loganalyser RSV2.log
          $BEAST/bin/treeannotator -burnin 20 -heights mean RSV2.trees RSV2.tree

      - name: hcv_coal
        # -l 40,000,000
        run: |
          $BEAST/bin/lphybeast -l 15000000 -o $XML_DIR/hcv_coal.xml $LPHY_SCRIPTS/hcv_coal.lphy
          cd $XML_DIR
          $BEAST/bin/beast -working -beagle_SSE -seed $SEED hcv_coal.xml
          ls -l
          $BEAST/bin/loganalyser hcv_coal.log
          $BEAST/bin/treeannotator -burnin 20 -heights mean hcv_coal.trees hcv_coal.tree

      # libgfortran5 is not working
      - name: Install libgfortran3
        run: sudo apt-get install libgfortran3
      - name: h3n2
        # -l 30,000,000
        run: |
          $BEAST/bin/lphybeast -l 10000000 -o $XML_DIR/h3n2.xml $LPHY_SCRIPTS/h3n2.lphy
          cd $XML_DIR
          $BEAST/bin/beast -working -beagle_SSE -seed $SEED h3n2.xml
          ls -l
          $BEAST/bin/loganalyser h3n2.log
          $BEAST/bin/treeannotator -burnin 20 -heights mean h3n2.mascot.trees h3n2.mascot.tree

      # check all *.log and *.tree
      - name: Test logs and trees
        run: ./gradlew test --no-daemon
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./**/build/test-results/**/*.xml
